#variables 
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de Teste",
  "description": "Essa é uma sala de Teste"
}

###
@roomId = {{createRoom.response.body.$.roomId}}

###

# Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/question
Content-Type: application/json

{
  "question": "Pergunta para Sala de Teste"
}
